Set with_dli option to False in Windows ARM profiles
- When trying to update apdfl-cpp-utils to Conan 2, the apdfl-cpp-utils
  bootstrap was running into the following error on Windows ARM:
    ConanException: Incorrect attempt to modify option 'with_dli' from 'True' to 'False'

- The APDFL conanfile.py does set the "with_dli" option to False in the configure() method, but
  my guess is this gets evaluated later and apdfl_cpp_utils is seeing the default value of the
  "with_dli" option which is set to "True" in APDFL. Let's set the option to "False" in the Windows
  ARM profile to get it applied early in the dependency resolution.